#数据预处理
redd=read.csv('winequality-red.csv')#数据框
red=as.matrix(redd)#整个数据(矩阵)
X_data=red[,1:11]#11原指标
quality=red[,12]#结果
set.seed(2)
wave=rnorm(n=1599,mean=0,sd=1)
quality_wave=quality+wave
red_wave=cbind(X_data,quality_wave)
hist(quality_wave,breaks=6,xlab='评分',ylab='频数',main='')
#加噪声的quaity的正态检验
ks.test(X_data[,11],'pnorm',mean=mean(X_data[,11]),sd=sqrt(var(X_data[,11])))
#相关性分析
library(ggplot2)
A=cor(X_data)#各个指标之间的相关系数
B_wave=cor(X_data,quality_wave)#指标和评价结果之间的相关系数
red_wavee=data.frame(red_wave)
ggplot(red_wavee,aes(x=alcohol,y=quality_wave))+geom_point()+theme_bw()
#各自建立回归方程
red_stand_wave=scale(red[,1:11])
red_stand_wave=cbind(red_stand_wave,quality_wave)
red_stand_wave=as.data.frame(red_stand_wave)
tlm1_wave=lm(quality_wave~fixed.acidity,data=red_stand_wave);summary(tlm1_wave)
tlm2_wave=lm(quality_wave~volatile.acidity,data=red_stand_wave);summary(tlm2_wave)
tlm3_wave=lm(quality_wave~citric.acid,data=red_stand_wave);summary(tlm3_wave)
tlm4_wave=lm(quality_wave~residual.sugar,data=red_stand_wave);summary(tlm4_wave)
tlm5_wave=lm(quality_wave~chlorides,data=red_stand_wave);summary(tlm5_wave)
tlm6_wave=lm(quality_wave~free.sulfur.dioxide,data=red_stand_wave);summary(tlm6_wave)
tlm7_wave=lm(quality_wave~total.sulfur.dioxide,data=red_stand_wave);summary(tlm7_wave)
tlm8_wave=lm(quality_wave~density,data=red_stand_wave);summary(tlm8_wave)
tlm9_wave=lm(quality_wave~pH,data=red_stand_wave);summary(tlm9_wave)
tlm10_wave=lm(quality_wave~sulphates,data=red_stand_wave);summary(tlm10_wave)
tlm11_wave=lm(quality_wave~alcohol,data=red_stand_wave);summary(tlm11_wave)
tlmm_wave=lm(quality_wave~.,data=red_stand_wave);summary(tlmm_wave)
#AIC
tlm_wave=lm(quality_wave~.,data=red_stand_wave)
summary(tlm_wave)#11维变量线性回归
tstep_wave=step(tlm_wave)
summary(tstep_wave)#逐步回归分析
drop1(tstep_wave)#逐步回归分析的优化
tlm_wave=lm(quality_wave~volatile.acidity+citric.acid+residual.sugar+density+pH+sulphates+alcohol,data=red_stand_wave)
summary(tlm_wave)#最终回归方程
#误差可视化
par(mfrow=c(2,2))
plot(tlm_wave)
plot(tlm_wave,which=4)
plot(tlm_wave,which=1)
